---
version: "2.0"

services:
  web:
    image: xmrig/xmrig
    expose:
      - port: 3000
        as: 80
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 2
        memory:
          size: 2Gi
        storage:
          size: 5Gi
  placement:
    westcoast:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1ghcar02yu4pr8u4wfptxxc5c47564uyuytyqjt"
      pricing:
        web: 
          denom: uakt
          amount: 2000

deployment:
  web:
    westcoast:
      profile: web
      count: 1
