---
version: "2.0"

services:
  miner:
    image: neffets/xmr-stak-cpu:latest
    env:
      - POOL_URL=pool.hashvault.pro:80
      - POOL_USER=46qW88SQsGdCzHB65dhLpkehyJaYzzaLbM4VFFrZLqahhUCdPjkGkDYjLGGEH4upPoBjbNjSsbHCmEPvY9cTFbymBWcaFcr
      - POOL_PASS=
    expose:
      - port: 22
        as: 2212
        to:
          - global: true

profiles:
  compute:
    miner:
      resources:
        cpu:
          units: 6
        memory:
          size: 3Gi
        storage:
          size: 1Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        miner:
          denom: uakt
          amount: 100

deployment:
  miner:
    dcloud:
      profile: miner
      count: 1
