---
version: "2.0"

services:
  web:
    image: MurcMurc/xmrig-docker
    expose:
      - port: 3000
        as: 80
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 2
        memory:
          size: 8Gi
        storage:
          size: 20Gi
  placement:
    westcoast:
      pricing:
        web: 
          denom: uakt
          amount: 2000

deployment:
  web:
    westcoast:
      profile: web
      count: 1
