---
version: "2.0"

services:
  miner:
    image: metal3d/xmrig:latest
    env:
      - POOL_URL=test
      - POOL_USER=test
      - POOL_PASS=test
    expose:
      - port: 22
        as: 2212
        to:
          - global: true

profiles:
  compute:
    miner:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          size: 20Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        miner:
          denom: uakt
          amount: 10

deployment:
  miner:
    dcloud:
      profile: miner
      count: 1
